name: Toolkit Tool Issue Report
description: Report an Issue with a Tool in the TypeScript Toolkit.
labels: ["issue", "toolkit"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in every section of the issue report completely.

        Before creating a new issue, ensure that you _thoroughly_ search through the [existing issues](https://github.com/FusedKush/typescript-toolkit/issues?q=is%3Aissue%20label%3Aissue%20label%3Atoolkit) and make sure your issue has not been reported already.

        Thank you for taking the time to submit this issue! If you think you might be able to resolve the issue yourself, considering [contributing](https://github.com/FusedKush/typescript-toolkit/tree/main/CONTRIBUTING.md)!.
  - type: textarea
    id: searchTerms
    attributes:
      label: Search Terms
      description: |
        Please list all of the search terms you used when searching through the existing issues.
        
        This will help others with the same problem find your issue easier.
      placeholder: |
        arrayify,
        toListString not working,
        UnionToIntersection doesn't work with x with y,
        etc...
    validations:
      required: true
  - type: dropdown
    id: tools
    attributes:
      label: Affected Tools
      description: Select all of the Tools in the TypeScript Toolkit that this issue applies to.
      multiple: true
      options:
        - "`arrays/ArrayifyType`"
        - "`arrays/arrayify()`"
        - "`arrays/toListString()`"
        - "`types/BaseType`"
        - "`types/BaseTypeString`"
        - "`types/getBaseType()`"
        - "`types/isBaseType()`"
        - "`types/assertBaseType()`"
        - "`types/IsAny`"
        - "`types/UnionToIntersection`"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of issue are you encountering?
      options:
        - Incorrect/Missing Documentation
        - Incorrect/Unexpected Behavior or Value
        - Undocumented Exception or Promise Rejection
        - Unsupported Function/Type Parameter Arguments
        - Other
    validations:
      required: true
  - type: textarea
    id: issueDescription
    attributes:
      label: Description of Issue
      description: |
        Please describe the bug, issue, or problem you have been experiencing.
      
        Please include as much information as possible in your report to help with understanding and resolving the issue, including:
        - The nature of the issue
        - How the issue affects client code
        - The affected source file(s), branch(es), and/or tag(s)
        - Any special files or configuration required for the issue to appear
        - Instructions to reproduce the issue
      placeholder: I was doing ... using ... with the intention of ... and then ... happened. 
    validations:
      required: true