name: Other Issue
description: Report an issue with TypeScript Toolkit not described by any of the Issue Templates.
labels: ["other issue"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in every section of the issue report completely.

        Before creating a new issue, ensure that you _thoroughly_ search through the [existing issues](https://github.com/FusedKush/typescript-toolkit/issues) and make sure your issue has not been reported already.

        Thank you for taking the time to submit this issue! If you think you might be able to resolve the issue yourself, considering [contributing](https://github.com/FusedKush/typescript-toolkit/tree/main/CONTRIBUTING.md)!.
  - type: textarea
    id: searchTerms
    attributes:
      label: Search Terms
      description: |
        Please list all of the search terms you used when searching through the existing issues.

        This will help others with the same problem find your issue easier.
    validations:
      required: true
  - type: checkboxes
    id: otherIssueAffirmation
    attributes:
      label: Other Issue Acknowledgement
      options:
        - label: I acknowledge that issues not matching any of the Issue Templates may be closed without explanation at the discretion of the project maintainers.
          required: true
    validations:
      required: true
  - type: textarea
    id: issueDescription
    attributes:
      label: Description of Issue
      description: |
        Please describe the bug, issue, or problem you have been experiencing.

        Please include as much information as possible in your report to help with understanding and resolving the issue, including:
        - The nature of the issue
        - How the issue affects client code
        - The affected source file(s), branch(es), and/or tag(s)
        - Any special files or configuration required for the issue to appear
        - Instructions to reproduce the issue
      placeholder: I was doing ... using ... with the intention of ... and then ... happened.
    validations:
      required: true
